### ISSUE TITLE
Please upgrade xml dependency 

### ISSUE THREAD

**Issue by jeromeDms** [dirablue/plist_parser#7]
Hi 
Is it possible to upgrade xml dependency to the latest ?
I'm using that xml dependency in my project, in addition to your parser.
there is a huge performance improvement in xml package, it could be nice to be able to use it.

Actually flutter complains about xml dependency in your package and does not allow to use latest xml package.
Thanks
Jerome

**Comment by dirablue** [comment]
Hi @jeromeDms 

Thank you for your suggestion.

Let me check it.

**Comment by dirablue** [comment]
hi @jeromeDms 

I updated XML dependency and Dart SDK version then published v0.0.8.
Thanks.
